[[dataset]]
# Class of the sampler. Must be of the form "your.module.YourSampler".
# The module must be importable from the current enviroment.
sampler = 'two4two.bias.MedVarSpherColorSampler'
# Save dataset to this directory.
output_dir = 'two4two_datasets/spherical_color_bias'

# Should be an existing output_dir be overwritten? [Default: false]
force_overwrite = false

# Number of concurrent processes.
n_processes = 6

# Should blender be downloaded? [Default: false]
download_blender = true

# Should the blender output be printed? [Default: false]
debug = false

# creates new dataset split names `train`.
[[dataset.split]]
name = 'train'
n_samples = 60_000

[[dataset.split]]
name = 'validation'
n_samples = 3_000

[[dataset.split]]
name = 'test'
n_samples = 3_000
interventions = [
    ['spherical'],
    ['obj_color'],
    ['spherical', 'obj_color'],
    ['arm_position'],
]
