[nobias]
sampler = 'two4two.Sampler'
output_dir = 'datasets/nobias'
n_processes = 6
download_blender = true
debug = false

[nobias.train]
n_samples = 60_000

[nobias.test]
n_samples = 10_000

[nobias.validation]
n_samples = 10_000
